import { router } from '@inertiajs/react';
import { Check, Copy, Send, Zap } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
    DialogTrigger,
} from '@/components/ui/dialog';

export function N8nSyncDialog({
    buttonVariant = 'outline',
    buttonSize = 'default',
    className = '',
}: {
    buttonVariant?: 'outline' | 'default' | 'ghost' | 'secondary';
    buttonSize?: 'default' | 'sm' | 'xs';
    className?: string;
}) {
    const [open, setOpen] = useState(false);
    const [loading, setLoading] = useState(false);
    const [sending, setSending] = useState(false);
    const [copied, setCopied] = useState(false);
    const [data, setData] = useState<{
        configured: boolean;
        webhook_url: string;
        payload: Record<string, unknown>;
    } | null>(null);

    useEffect(() => {
        if (open && !data) {
            setLoading(true);
            fetch('/n8n/preview')
                .then((res) => res.json())
                .then((res) => {
                    setData(res);
                    setLoading(false);
                })
                .catch(() => setLoading(false));
        }
    }, [open, data]);

    const handleCopy = () => {
        if (!data?.payload) return;
        navigator.clipboard.writeText(JSON.stringify(data.payload, null, 2));
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const handleSend = () => {
        setSending(true);
        router.post(
            '/n8n/sync-now',
            {},
            {
                onFinish: () => {
                    setSending(false);
                    setOpen(false);
                },
            },
        );
    };

    const jsonString = data?.payload ? JSON.stringify(data.payload, null, 2) : '';

    return (
        <Dialog open={open} onOpenChange={setOpen}>
            <DialogTrigger asChild>
                <Button
                    variant={buttonVariant}
                    size={buttonSize}
                    className={`gap-1.5 font-semibold hover:border-amber-500/50 hover:bg-amber-500/10 cursor-pointer ${className}`}
                >
                    <Zap className="size-3.5 fill-amber-500 text-amber-500" />
                    Push to n8n
                </Button>
            </DialogTrigger>

            <DialogContent className="max-w-2xl max-h-[85vh] flex flex-col">
                <DialogHeader>
                    <DialogTitle className="flex items-center gap-2 text-base font-bold">
                        <Zap className="size-4 fill-amber-500 text-amber-500" />
                        Push Empty Rooms to n8n Webhook
                    </DialogTitle>
                    <DialogDescription className="text-xs">
                        Preview the exact JSON payload generated by OpenKos before pushing to n8n.
                    </DialogDescription>
                </DialogHeader>

                {/* Target Webhook Status Banner */}
                <div className="flex items-center justify-between gap-3 rounded-lg border border-border/80 bg-muted/30 px-3.5 py-2.5 text-xs">
                    <span className="font-semibold text-muted-foreground truncate">
                        Target URL:{' '}
                        <span className="font-mono text-foreground">
                            {data?.webhook_url || 'Loading...'}
                        </span>
                    </span>
                    {data && (
                        <Badge
                            variant={data.configured ? 'default' : 'destructive'}
                            className="text-[10px] uppercase font-bold shrink-0"
                        >
                            {data.configured ? 'Webhook Configured' : 'Missing URL in .env'}
                        </Badge>
                    )}
                </div>

                {/* JSON Code Box */}
                <div className="relative flex-1 overflow-hidden rounded-lg border border-border/80 bg-slate-950 p-4 text-xs text-slate-100 dark:bg-slate-900 font-mono">
                    {loading ? (
                        <div className="flex h-48 items-center justify-center text-muted-foreground text-xs">
                            Generating JSON payload preview...
                        </div>
                    ) : (
                        <div className="max-h-72 overflow-y-auto pr-2 space-y-1">
                            <pre className="whitespace-pre-wrap break-words leading-relaxed text-[11px]">
                                {jsonString}
                            </pre>
                        </div>
                    )}
                </div>

                <DialogFooter className="flex items-center justify-between gap-2 border-t border-border/60 pt-3">
                    <Button
                        type="button"
                        variant="outline"
                        size="sm"
                        onClick={handleCopy}
                        disabled={!jsonString}
                        className="gap-1.5 text-xs cursor-pointer"
                    >
                        {copied ? (
                            <Check className="size-3.5 text-emerald-500" />
                        ) : (
                            <Copy className="size-3.5" />
                        )}
                        {copied ? 'Copied to Clipboard!' : 'Copy JSON'}
                    </Button>

                    <Button
                        type="button"
                        variant="default"
                        size="sm"
                        onClick={handleSend}
                        disabled={sending || !data?.configured}
                        className="gap-1.5 text-xs font-semibold cursor-pointer"
                    >
                        <Send className="size-3.5" />
                        {sending ? 'Sending Payload...' : 'Send / Push to n8n Now'}
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
}
